<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_()_user_pob</name>
   <tag></tag>
   <elementGuidId>0b210d4b-57fb-442d-8ebd-f49d435a219d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#user_pob</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='user_pob']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>73906289-6cca-4135-848f-4710c295d354</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f6517ab4-608e-4fe9-9376-b39ed5e6ebd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>e12a962f-3da6-41e7-aebc-f95925a67b9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>user_pob</value>
      <webElementGuid>4d53cddd-c962-41a2-88cf-2bf7ecf5f515</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>user_pob</value>
      <webElementGuid>44b2aa45-8070-4400-a477-d06cc35992db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Tempat Lahir</value>
      <webElementGuid>48273ef2-e28a-4594-951f-11e99c982968</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;user_pob&quot;)</value>
      <webElementGuid>af069b75-f70b-4d78-85f9-c24f0325794e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='user_pob']</value>
      <webElementGuid>fcbe8a46-28cd-4be3-9bf4-9c46c1012f13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div_user_data']/fieldset/div/div/div/div[6]/div/input</value>
      <webElementGuid>5e3c98c8-77b3-4427-821f-f367d8360246</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/input</value>
      <webElementGuid>b7d7fac1-3bd5-49eb-bc2a-2d870bc16133</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'user_pob' and @name = 'user_pob' and @placeholder = 'Tempat Lahir']</value>
      <webElementGuid>26db98b9-8267-4ffe-b4f3-931961ab77a1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
