<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_()_nip</name>
   <tag></tag>
   <elementGuidId>d32c83fb-53dc-45bc-9141-0f2b956fe97a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nip</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='nip']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e00a71a0-807d-4d6e-b1c5-9df6b6dbd8fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2626f842-0497-4ff2-be11-ac20a9b6d937</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>a4434bdb-2927-4e6f-b9f2-3c513ef9490a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nip</value>
      <webElementGuid>88861f26-e950-4ed1-b5dd-104cbbd59b4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>nip</value>
      <webElementGuid>a0110fd9-ae92-448a-b2d5-5b86dfd4e5cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>NRP/NIP</value>
      <webElementGuid>6573ce98-2cd6-4c6a-88dd-3669fcf7afd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>b03a0e0e-1444-4c64-8e56-463b0c9e1b25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nip&quot;)</value>
      <webElementGuid>ccde7fb3-f538-477c-aa7e-e98e31e27d65</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='nip']</value>
      <webElementGuid>55522551-a87b-4897-9af1-d4529d3978b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='employee_data']/div/div/div/input</value>
      <webElementGuid>1204875e-16be-47a4-928b-c4ffdebc3fab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[19]/div/div/div/input</value>
      <webElementGuid>609d080c-1119-4e35-9da8-1ea45eff668c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'nip' and @name = 'nip' and @placeholder = 'NRP/NIP']</value>
      <webElementGuid>5c4c5d16-d499-43eb-87b8-b8eaa021acec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
