<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_()_user_hp</name>
   <tag></tag>
   <elementGuidId>78002626-003c-413f-bf18-bf5813bcd169</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#user_hp</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='user_hp']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>37591e5a-0bfd-4bb5-8424-973da3a2b2b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>05b4374a-28cf-4bef-99f7-582bbcc5e01e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>af5ea091-e405-4d26-add3-611f3d2e2f00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>user_hp</value>
      <webElementGuid>2556d7b5-d93c-4ed6-9b1a-9f1ad1dc6c68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>user_hp</value>
      <webElementGuid>0fd5457c-d0c4-48e5-ad1c-4b95ff049041</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>if ( isNaN( String.fromCharCode(event.keyCode) )) return false;</value>
      <webElementGuid>0575e285-241a-41d5-a114-82a6a0b35286</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>No Handphone</value>
      <webElementGuid>e74be297-440f-404d-ab46-aa5e011e9dcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;user_hp&quot;)</value>
      <webElementGuid>8a5e61fe-714e-4605-befb-becf356cff37</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='user_hp']</value>
      <webElementGuid>89f837ff-a4a9-47d0-b852-db84f6930827</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div_user_data']/fieldset/div/div/div/div[10]/div[2]/input</value>
      <webElementGuid>03e4eca7-1989-416d-9766-9218831e5998</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div[2]/input</value>
      <webElementGuid>1645f41e-6fc3-4b56-a320-00ac3dfba4dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'user_hp' and @name = 'user_hp' and @placeholder = 'No Handphone']</value>
      <webElementGuid>22d997f6-c462-4e1d-a1a5-98679914e552</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
