<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_()_emp_position</name>
   <tag></tag>
   <elementGuidId>076e09ef-71df-43cf-a445-95d03e20976d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#emp_position</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='emp_position']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c121a7a8-0421-4fe6-8862-ac80011ca41b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>39e2a775-81e4-48b7-8e42-68025d0b43bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>7de787b6-9946-47ae-b709-502e5f2aee35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>emp_position</value>
      <webElementGuid>ef4ff8ee-0566-45b8-9e99-749870cf2801</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>emp_position</value>
      <webElementGuid>34b6c3a1-4916-4d10-aae8-c1a85a79243f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Isi Jabatan</value>
      <webElementGuid>ec9ed5a3-4175-4741-bd27-6d607200c476</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;emp_position&quot;)</value>
      <webElementGuid>68fd200f-f3a7-4086-a507-45c4a4acbc8f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='emp_position']</value>
      <webElementGuid>16c3d199-b03a-4d11-804c-56abb05a1d58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='employee_data']/div[3]/div/div/input</value>
      <webElementGuid>d9dbe096-210d-4d0d-a6d3-5750a1dc40e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/input</value>
      <webElementGuid>782a53b6-34d1-48e6-81c9-1d7b1a5ffada</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'emp_position' and @name = 'emp_position' and @placeholder = 'Isi Jabatan']</value>
      <webElementGuid>ec864e3b-5587-489b-89a8-9fca87be0239</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
