<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_()_user_dob</name>
   <tag></tag>
   <elementGuidId>47b90d68-9a97-45bc-a25c-6503c73627ef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#user_dob</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='user_dob']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1490484c-c22d-491c-95b2-51379d7e6f7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>741f7c3b-8ac9-4d2b-b3f6-fdcc5e097e23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control datepicker</value>
      <webElementGuid>baafcf73-0223-4f8d-bf16-6ae4d7e19bb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>user_dob</value>
      <webElementGuid>b0afac50-66e7-4c81-9c18-763ba2ed68c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>user_dob</value>
      <webElementGuid>d2ea1511-8bd4-4891-828a-ffa08771bb1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>dd/mm/yyyy</value>
      <webElementGuid>d044c068-02ff-47bb-8b39-04d9528ce71b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>2abe5800-00af-4ac0-8dc5-15ce866502c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;user_dob&quot;)</value>
      <webElementGuid>89b0b2bd-66ff-4863-9f4a-da97a964f482</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='user_dob']</value>
      <webElementGuid>439e1076-4cd1-43ca-a1e4-4fcd474430e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div_user_data']/fieldset/div/div/div/div[6]/div[2]/input</value>
      <webElementGuid>619a2d8e-f847-493b-bf5a-dc9ac93fc6ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]/input</value>
      <webElementGuid>1286af36-e308-412a-a5c6-22486e3426fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'user_dob' and @name = 'user_dob' and @placeholder = 'dd/mm/yyyy']</value>
      <webElementGuid>b41aa634-9120-4894-b559-ca6e476cca3d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
