<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Juru Muda</name>
   <tag></tag>
   <elementGuidId>55c38d93-bca9-49be-a8df-dad8ff733df5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-emp_grade-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-emp_grade-container']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>0a33ff7f-4ab3-4e15-8bb3-f0e6defbe66a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>de95d65b-0f7e-4726-858a-156db1ff7234</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-emp_grade-container</value>
      <webElementGuid>746fc388-da50-4489-aa29-88b17e8077f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>38aafb64-6a81-4c9d-a08a-df6e0f8e8127</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>2d8aa258-424e-4839-8f82-b86a75f9cc3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Juru Muda</value>
      <webElementGuid>a7264f59-70f0-44c5-8ea3-d3e80b064d76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>×Juru Muda</value>
      <webElementGuid>5ee8e16d-7052-4b74-a89a-8242ca6ab6b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-emp_grade-container&quot;)</value>
      <webElementGuid>6c10317d-4575-493b-96c5-8b1bbb0fe74c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-emp_grade-container']</value>
      <webElementGuid>498ac560-a2d4-48c1-9304-7bd38fd99596</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='employee_data']/div[2]/div/div/span/span/span/span</value>
      <webElementGuid>64725bfb-c127-45fa-b1ad-bcae955a793e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(*)'])[10]/following::span[4]</value>
      <webElementGuid>126b5ec8-1a7f-4fd7-9791-0696e6218b94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/span/span/span/span</value>
      <webElementGuid>ee904496-9a4a-48ec-95b5-12973f81ce27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-emp_grade-container' and @title = 'Juru Muda' and (text() = '×Juru Muda' or . = '×Juru Muda')]</value>
      <webElementGuid>0c7c277f-1060-43b6-a36f-25a6e60f1e9c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
