<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Penata Tingkat 1</name>
   <tag></tag>
   <elementGuidId>e678a538-5a25-4d42-b719-726c59dec42d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-emp_grade-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-emp_grade-container']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>2ee1e370-ef5e-4839-8c7c-75aae0347cb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>7793ce4b-8383-489a-99ab-ee641ae6df4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-emp_grade-container</value>
      <webElementGuid>c7bd30e5-8581-46b4-bc2d-31a22e65d671</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>c7b2c551-76f0-40bf-b8eb-0734992323d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>bf459fcd-3444-45ea-b935-9a5873d03120</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Penata Tingkat 1</value>
      <webElementGuid>52b3515b-ec96-4fe0-971c-8973420dcd01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>×Penata Tingkat 1</value>
      <webElementGuid>8b0c0f16-ee10-446e-8970-60e0d71e80aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-emp_grade-container&quot;)</value>
      <webElementGuid>d1b2353c-1fac-4c7f-999f-96ce0a65319f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-emp_grade-container']</value>
      <webElementGuid>cc0ee95d-f558-46cd-b427-f2a84e2eecd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='employee_data']/div[2]/div/div/span/span/span/span</value>
      <webElementGuid>a8d3b3b3-0a83-4ba9-b64f-a4a5aaee4dd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(*)'])[10]/following::span[4]</value>
      <webElementGuid>0df4b9cf-3253-457c-ad1c-5f24e8c5172b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/span/span/span/span</value>
      <webElementGuid>9ff2fb24-b487-4dd5-9757-b0c74d27c4e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-emp_grade-container' and @title = 'Penata Tingkat 1' and (text() = '×Penata Tingkat 1' or . = '×Penata Tingkat 1')]</value>
      <webElementGuid>1b00bc6d-8e16-471e-906a-31c174aa3935</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
