<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Pencarian_1</name>
   <tag></tag>
   <elementGuidId>b7c0a93d-aa27-463f-94d7-f347de47eb07</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-emp_grade-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-emp_grade-container']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>00bea757-44ef-468d-b3c5-34d030558f3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>156c777d-0f79-4ef5-b707-329bfcd09942</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-emp_grade-container</value>
      <webElementGuid>79eb21ed-b7d6-41a9-b4fd-64f2b37aaa8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>7722ec68-8d38-4e6d-8acf-7b4d66fa5af2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>6ddd011e-6e19-4eaf-8650-1816f4045837</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pencarian...</value>
      <webElementGuid>54232c90-a6ec-4fcc-9b3f-33f7478295cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-emp_grade-container&quot;)</value>
      <webElementGuid>424e5b70-afbe-4d3b-aaff-9dbe575ee38e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-emp_grade-container']</value>
      <webElementGuid>fb6da9f5-e1d9-4767-a0d2-86467009073d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='employee_data']/div[2]/div/div/span/span/span/span</value>
      <webElementGuid>80e769fe-376c-4870-9ba2-4d98418a7c2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(*)'])[10]/following::span[4]</value>
      <webElementGuid>9e14ee54-325d-42fc-8e7d-8e8407fa1510</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/span/span/span/span</value>
      <webElementGuid>b8d7d6ba-4aa9-44a2-9a3e-18a90f6dc60a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-emp_grade-container' and (text() = 'Pencarian...' or . = 'Pencarian...')]</value>
      <webElementGuid>999ba60b-4aa0-45da-93e0-de3f29807fc7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
