<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Password_fa fa-eye-slash</name>
   <tag></tag>
   <elementGuidId>f591b720-a6e4-45df-918f-e9ecff8e5f22</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='show_hide_password']/div/span/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.fa.fa-eye-slash</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>59c77e1e-5354-442e-8f53-9a1a0f25ce38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-eye-slash</value>
      <webElementGuid>4edccda8-4717-42f9-b09b-0ce0d572f505</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c8ff2a7f-7ac6-4b7d-88ae-cb21730f9225</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;show_hide_password&quot;)/div[@class=&quot;input-group-append&quot;]/span[@class=&quot;input-group-login-eye&quot;]/i[@class=&quot;fa fa-eye-slash&quot;]</value>
      <webElementGuid>1d3618a8-0eab-4022-85d9-c904a1f22745</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='show_hide_password']/div/span/i</value>
      <webElementGuid>d469973b-7835-478e-8885-ca17463489de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//i</value>
      <webElementGuid>d5efb9ee-6d43-4ad6-95c3-317de7f25590</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
