<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea__dayoff_name</name>
   <tag></tag>
   <elementGuidId>05681ab5-2ca0-4e96-9f5a-8e7d256aeaa7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='dayoff_name']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#dayoff_name</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>cf78b4d3-0acb-4024-b90f-a488ad0d5988</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dayoff_name</value>
      <webElementGuid>1b448740-2124-4c4b-8741-2ea7e3cd96e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dayoff_name</value>
      <webElementGuid>050dcf74-6e5b-49c5-9cd3-cf68b4c18c8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>53a45387-5d71-48a8-9a8d-b96b829fb490</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>f375c326-5c86-4b9f-93d5-e36a2e00b939</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>500</value>
      <webElementGuid>413185c0-7dfc-4c43-a01f-2de2579ab17e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Keterangan</value>
      <webElementGuid>649f8a43-3c0a-4ae9-88fc-d279aa10d783</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dayoff_name&quot;)</value>
      <webElementGuid>4336f61e-99fa-446f-9567-734467ee95ce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='dayoff_name']</value>
      <webElementGuid>81e79f17-ce52-4005-8cb9-f085b75490bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='f1']/div[2]/textarea</value>
      <webElementGuid>6e6d4a55-77bf-4265-a0c9-594e31ee4c67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>b806d3aa-1bc4-42c6-bf00-bf8f88178d2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'dayoff_name' and @id = 'dayoff_name' and @placeholder = 'Keterangan']</value>
      <webElementGuid>35178515-54ca-4e60-a546-f962316b077b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
