<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_No Telepon_unit_phone</name>
   <tag></tag>
   <elementGuidId>c506b664-2e3a-4d1d-a011-d9817347c4d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='unit_phone']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#unit_phone</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>670c417d-8103-4761-bc0d-6c64e15f9fd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>13dece4b-6614-40eb-a959-1da7fb4af294</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>unit_phone</value>
      <webElementGuid>647cfd72-a508-478b-a6fc-a6288294f31b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>unit_phone</value>
      <webElementGuid>ed987af0-43f4-4fe2-be53-cf05f7bd6185</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>13</value>
      <webElementGuid>c05f920b-45e4-45bc-a262-60d4470b885d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>if ( isNaN( String.fromCharCode(event.keyCode) )) return false;</value>
      <webElementGuid>3edb0a81-e117-4ef2-816b-e800735ca47e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>2efe9919-01ca-428b-b814-fad507e02458</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>No Telepon</value>
      <webElementGuid>6f9f844f-8b3e-4308-a870-cd80c6f79d2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;unit_phone&quot;)</value>
      <webElementGuid>de38046c-4ae7-4fec-b9c9-7002f02fee7a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='unit_phone']</value>
      <webElementGuid>6406490d-cf70-4edc-a8b6-e29990ebe22b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='f1']/div[4]/input</value>
      <webElementGuid>fb2e8083-8fa3-4130-9bf9-31d045ed070a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>7fc88fdf-67fc-4052-b679-d09b0861191b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'unit_phone' and @id = 'unit_phone' and @placeholder = 'No Telepon']</value>
      <webElementGuid>878262a0-6ec4-4f56-9067-b3703a27f422</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
