<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Fungsi_scale_label</name>
   <tag></tag>
   <elementGuidId>5251c6ef-cdb1-4931-8645-0b29b57b1c4d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='scale_label']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#scale_label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>08dd88ba-49ae-4fe5-bf22-c1ba97890b6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fc35e413-19ca-4356-aa98-eb59d438edd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>83780bb5-e7b4-4017-80e2-2d3e082669a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>16099823-7a94-43e0-8f9f-a59657cb19d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>scale_label[]</value>
      <webElementGuid>7da2a03a-5ec0-4854-a6cb-851061ebcc65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>scale_label</value>
      <webElementGuid>b8f2921c-5b96-4cc8-beb2-65b920408a28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;scale_label&quot;)</value>
      <webElementGuid>03ba0085-3956-480a-848e-ae1fbffffe4d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='scale_label']</value>
      <webElementGuid>0a8dea59-6dab-4e10-87e2-4324bce9acb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tableWrapper']/tbody/tr/td/div/input</value>
      <webElementGuid>0d9e3570-af67-47a9-8a92-83ea39b2d2e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div/input</value>
      <webElementGuid>7650aecb-429d-4b3b-9904-c92223676904</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'scale_label[]' and @id = 'scale_label']</value>
      <webElementGuid>5a35032c-86e8-4ff9-a9fd-d10762dbc67d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
