<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Fungsi_scale_minimum (2)</name>
   <tag></tag>
   <elementGuidId>e50debea-6286-4d45-bad4-26cc27f9c4d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='scale_minimum'])[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>eb5148b7-2de7-4167-ab65-b9b96dbb3b2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>79f29427-ef0b-420e-80a6-4b71ad58a905</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>91a50369-0fb1-4f8d-966e-3c7f184ffde8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>69bd5d9c-1b15-484f-b8ba-2b34b4c77224</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>scale_minimum[]</value>
      <webElementGuid>cc3bf4bc-1e35-40b6-8ac8-751081f45648</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>scale_minimum</value>
      <webElementGuid>7c526f49-15e3-4113-b7f8-406b3f953aa3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>1a06d1ca-3b7e-41fe-b805-ad21ca88e27a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tableWrapper&quot;)/tbody[1]/tr[@class=&quot;score-data&quot;]/td[3]/div[@class=&quot;mb-3&quot;]/input[@id=&quot;scale_minimum&quot;]</value>
      <webElementGuid>ee16870f-4b7e-4fc9-a490-33bf5db983f8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='scale_minimum'])[3]</value>
      <webElementGuid>d67815ad-df77-4d76-9bac-45d6ef2dd764</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tableWrapper']/tbody/tr[3]/td[3]/div/input</value>
      <webElementGuid>75a6a1ad-9ac5-485a-acdc-76c967cb55e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[3]/div/input</value>
      <webElementGuid>35a17c46-d59b-4c7a-bc5b-bb45be2a83cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'scale_minimum[]' and @id = 'scale_minimum']</value>
      <webElementGuid>6a367b1b-271a-47f0-9aa4-c78d5a95844a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
