<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Fungsi_scale_minimum (1)</name>
   <tag></tag>
   <elementGuidId>3b7bbc5a-eb27-4058-8f58-7d4cf7482f18</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='scale_minimum'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a3978183-cc25-456b-b58c-d1c7fe434f5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>ec17b95c-efc0-417c-ab24-85ee907ac991</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>fc0004ae-ff2f-4c39-9135-c8ccfc7600b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>f78905b5-60ef-460a-a1bd-2bdfc58bdb2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>scale_minimum[]</value>
      <webElementGuid>188c28bb-1353-43f5-a845-b8da8018f78c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>scale_minimum</value>
      <webElementGuid>836dfc64-d8b8-4037-820a-2bf6f0cfddc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>cc2c4911-102c-4e92-ae61-01cc2c688184</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tableWrapper&quot;)/tbody[1]/tr[@class=&quot;score-data&quot;]/td[3]/div[@class=&quot;mb-3&quot;]/input[@id=&quot;scale_minimum&quot;]</value>
      <webElementGuid>bdb725b8-5d41-4975-b532-f019878afe11</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='scale_minimum'])[2]</value>
      <webElementGuid>8032bfca-7405-4ab8-8ff2-c086b64b3edd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tableWrapper']/tbody/tr[2]/td[3]/div/input</value>
      <webElementGuid>8006aa22-158a-48ca-97cc-83b5f2de1b3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[3]/div/input</value>
      <webElementGuid>ce254951-c9a2-49f4-90b7-4eea18f8635a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'scale_minimum[]' and @id = 'scale_minimum']</value>
      <webElementGuid>8d450d14-3360-4df5-98bc-7f3356c8e256</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
